print("Hello world")
print("What's your name? ")
name = input()
print("my name is " + name)
print('The length of your name is ')
print(len(name))
print("how old are you")
age = input()
print("you will be " + str(int(age) + 1) + " in a year")